Neos:
  Flow:
    mvc:
      routes:
        'PunktDe.Neos.AdvancedSearch':
          position: 'before Neos.Neos'
  Fusion:
    defaultContext:
      NodeAddress: PunktDe\Neos\AdvancedSearch\Eel\NodeAddressHelper
