PunktDe:
  Search:
    AlternativeSearchWords:
      stopWordFolders:
        languageFolder: '%FLOW_PATH_PACKAGES%/Application/PunktDe.Search.AlternativeSearchWords/Resources/Private/StopWords'
        # All files within this folder are loaded
        customerSpecificFolder: ''

