PunktDe:
  Neos:
    AdvancedSearch:
      stopWordFolders:
        languageFolder: '%FLOW_PATH_PACKAGES%/Application/PunktDe.Neos.AdvancedSearch/Resources/Private/StopWords'
        # All files within this folder are loaded
        customerSpecificFolder: ''

